# Generated by Django 5.1.6 on 2025-06-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineeringapi', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
